#Use the Rotterdam breast cancer data set, available from https://www.imbi.uni-freiburg.de/Royston-Sauerbrei-book/index.html#datasets
#It is called rotterdam_br_ca and I used the csv version

#packages and load data

```{r}
library(rms)
library(survival)
library(smcfcs)
library(mice)
library(timereg)
library(mitools)
library(stringr)

mydata=read.table("rotterdam_br_ca.csv",header=T,sep=",")

#rename variables
mydata$t=mydata$X_t
mydata$d=mydata$X_d

#drop variables not used

mydata=mydata[,-c(16:19)]

#VARIABLES TO BE USED
#age, sized2, grade, enodes_sq, hormon, chemo, sized1, log(pgr+1)

n=dim(mydata)[1]

#transformed variables
mydata$enodessq=mydata$enodes^2
mydata$logpgr=log(mydata$pgr+1)

#split data on event time
range(mydata$t[mydata$d==1])
cut.points=seq(0,15,0.5)
mydata.split=survSplit(Surv(t,d)~.,mydata,cut=cut.points)
mydata.split=mydata.split[mydata.split$t>mydata.split$tstart,]

```


#-------------------------------------------
#-------------------------------------------
#generate missingness - MAR
#-------------------------------------------
#-------------------------------------------

```{r}
set.seed(67243)

expit=function(x){exp(x)/(1+exp(x))}

miss.grade=rbinom(n,1,expit(-9+0.1*mydata$age-1*(mydata$sized2==1)))
miss.enodessq=rbinom(n,1,expit(-9+0.1*mydata$age-1*(mydata$sized2==1)))
miss.hormon=rbinom(n,1,expit(-9+0.1*mydata$age-1*(mydata$sized2==1)))
miss.chemo=rbinom(n,1,expit(-9+0.1*mydata$age-1*(mydata$sized2==1)))
miss.logpgr=rbinom(n,1,expit(-9+0.1*mydata$age-1*(mydata$sized2==1)))
sum(miss.grade)/n
sum(miss.enodessq)/n
sum(miss.hormon)/n
sum(miss.chemo)/n
sum(miss.logpgr)/n

mydata$grade=ifelse(miss.grade==1,NA,mydata$grade)
mydata$enodessq=ifelse(miss.enodessq==1,NA,mydata$enodessq)
mydata$hormon=ifelse(miss.hormon==1,NA,mydata$hormon)
mydata$chemo=ifelse(miss.chemo==1,NA,mydata$chemo)
mydata$logpgr=ifelse(miss.logpgr==1,NA,mydata$logpgr)

```

#-------------------------------------------
#-------------------------------------------
#generate spline functions for TVEs
#-------------------------------------------
#-------------------------------------------

```{r}
knots.5=quantile(mydata$t[mydata$d==1],probs=c(0.05,0.25,0.5,0.75,0.95))
knots.4=quantile(mydata$t[mydata$d==1],probs=c(0.05,0.33,0.66,0.95))
knots.3=quantile(mydata$t[mydata$d==1],probs=c(0.10,0.5,0.90))

###
knots.5.eval=rcspline.eval(mydata$t,knots=knots.5)
knots.4.eval=rcspline.eval(mydata$t,knots=knots.4)
knots.3.eval=rcspline.eval(mydata$t,knots=knots.3)

mydata$t.k5.1=knots.5.eval[,1]
mydata$t.k5.2=knots.5.eval[,2]
mydata$t.k5.3=knots.5.eval[,3]

mydata$t.k4.1=knots.4.eval[,1]
mydata$t.k4.2=knots.4.eval[,2]

mydata$t.k3=knots.3.eval[,1]

###
knots.5.eval=rcspline.eval(mydata.split$t,knots=knots.5)
knots.4.eval=rcspline.eval(mydata.split$t,knots=knots.4)
knots.3.eval=rcspline.eval(mydata.split$t,knots=knots.3)

mydata.split$t.k5.1=knots.5.eval[,1]
mydata.split$t.k5.2=knots.5.eval[,2]
mydata.split$t.k5.3=knots.5.eval[,3]

mydata.split$t.k4.1=knots.4.eval[,1]
mydata.split$t.k4.2=knots.4.eval[,2]

mydata.split$t.k3=knots.3.eval[,1]

```

#-------------------------------------------
#-------------------------------------------
#perform imputation - TVE-SMC
#-------------------------------------------
#-------------------------------------------

```{r}

#recode grade as 0/1 instead of 2/3
mydata$grade=ifelse(mydata$grade==2,0,mydata$grade)
mydata$grade=ifelse(mydata$grade==3,1,mydata$grade)

mydata$dt=mydata$d*mydata$t
mydata$dt.sp5.1=mydata$d*mydata$t.k5.1
mydata$dt.sp5.2=mydata$d*mydata$t.k5.2
mydata$dt.sp5.3=mydata$d*mydata$t.k5.3

method=as.matrix(rep("",dim(mydata)[2]))
rownames(method)=names(mydata)
method[c("grade","enodessq","hormon","chemo","logpgr"),]=c("logreg","norm","logreg","logreg","norm")
pred.mat=matrix(0,nrow=length(method),ncol=length(method))
colnames(pred.mat)=names(mydata)
rownames(pred.mat)=names(mydata)
pred.mat["grade",c("age","sized1","sized2","enodessq","hormon","chemo","logpgr")]=1
pred.mat["enodessq",c("age","sized1","sized2","grade","hormon","chemo","logpgr")]=1
pred.mat["hormon",c("age","sized1","sized2","grade","enodessq","chemo","logpgr")]=1
pred.mat["chemo",c("age","sized1","sized2","grade","enodessq","hormon","logpgr")]=1
pred.mat["logpgr",c("age","sized1","sized2","grade","enodessq","hormon","chemo")]=1

set.seed(46713)
nimp=20
mi.dat=smcfcs.tve(originaldata=mydata,id="pid",smformula.timefixed="Surv(t, d) ~ age+sized1+sized2+grade+enodessq+hormon+chemo+logpgr",
       method=method,tvar=c("age","sized1","sized2","grade","enodessq","hormon","chemo","logpgr"),tvarfunc=NULL,
       spline=T,knots=NULL,nknots=5,
       predictorMatrix = pred.mat,m=nimp,numit=5,rjlimit=1000,noisy=F,quick=F,quick.cuts=NULL)

#NOTE: THE IMPUTATION IS SLOW!

```
##




#-------------------------------------------
#-------------------------------------------
#MODEL SELECTION PROCEDURE
#-------------------------------------------
#-------------------------------------------

#------------------
#model with k5-spline for all variables
#------------------

```{r}
variable.list=c("age","sized1","sized2","grade","enodessq","hormon","chemo","logpgr")
varlist.t=paste0(variable.list,":t")
varlist.k5.1=paste0(variable.list,":t.k5.1")
varlist.k5.2=paste0(variable.list,":t.k5.2")
varlist.k5.3=paste0(variable.list,":t.k5.3")

formula.full=as.formula(paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"),"+",paste0(varlist.t,collapse="+"),"+",paste0(varlist.k5.1,collapse="+"),
                               "+",paste0(varlist.k5.2,collapse="+"),"+",paste0(varlist.k5.3,collapse="+")))

mi.fullmod.coef=matrix(nrow=nimp,ncol=40)
mi.fullmod.varcov=array(dim=c(nimp,40,40))

for(imp in 1:nimp){
  
  print(imp)
  temp=survSplit(Surv(t,d)~.,mi.dat$impDatasets[[imp]],cut=cut.points)
  temp=temp[temp$t>temp$tstart,]
  temp$t.k5.1=mydata.split$t.k5.1
  temp$t.k5.2=mydata.split$t.k5.2
  temp$t.k5.3=mydata.split$t.k5.3
  temp$t.k4.1=mydata.split$t.k4.1
  temp$t.k4.2=mydata.split$t.k4.2
  temp$t.k3=mydata.split$t.k3

  mi.fullmod=coxph(as.formula(formula.full),data=temp)
  
  mi.fullmod.coef[imp,]=mi.fullmod$coef
 
  mi.fullmod.varcov[imp,,]=vcov(mi.fullmod)
  
}
  
fullmod.miSMCTVE=MIcombine(eval(parse(text=paste0("list(",paste0("mi.fullmod.coef[",1:nimp,",]",collapse=","),")"))),                               eval(parse(text=paste0("list(",paste0("mi.fullmod.varcov[",1:nimp,",,]",collapse=","),")"))))

varlist.full=c(variable.list,varlist.t,varlist.k5.1,varlist.k5.2,varlist.k5.3)

age.varlist=c("age","age:t","age:t.k5.1","age:t.k5.2","age:t.k5.3")
sized1.varlist=c("sized1","sized1:t","sized1:t.k5.1","sized1:t.k5.2","sized1:t.k5.3")
sized2.varlist=c("sized2","sized2:t","sized2:t.k5.1","sized2:t.k5.2","sized2:t.k5.3")
grade.varlist=c("grade","grade:t","grade:t.k5.1","grade:t.k5.2","grade:t.k5.3")
enodessq.varlist=c("enodessq","enodessq:t","enodessq:t.k5.1","enodessq:t.k5.2","enodessq:t.k5.3")
hormon.varlist=c("hormon","hormon:t","hormon:t.k5.1","hormon:t.k5.2","hormon:t.k5.3")
chemo.varlist=c("chemo","chemo:t","chemo:t.k5.1","chemo:t.k5.2","chemo:t.k5.3")
logpgr.varlist=c("logpgr","logpgr:t","logpgr:t.k5.1","logpgr:t.k5.2","logpgr:t.k5.3")

names(fullmod.miSMCTVE$coefficients)=varlist.full
colnames(mi.fullmod.coef)=varlist.full
dimnames(mi.fullmod.varcov)[[2]]=varlist.full
dimnames(mi.fullmod.varcov)[[3]]=varlist.full

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[age.varlist[2:5]]
all.coef=mi.fullmod.coef[,age.varlist[2:5]]
all.var=mi.fullmod.varcov[,age.varlist[2:5],age.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[sized1.varlist[2:5]]
all.coef=mi.fullmod.coef[,sized1.varlist[2:5]]
all.var=mi.fullmod.varcov[,sized1.varlist[2:5],sized1.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[sized2.varlist[2:5]]
all.coef=mi.fullmod.coef[,sized2.varlist[2:5]]
all.var=mi.fullmod.varcov[,sized2.varlist[2:5],sized2.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[grade.varlist[2:5]]
all.coef=mi.fullmod.coef[,grade.varlist[2:5]]
all.var=mi.fullmod.varcov[,grade.varlist[2:5],grade.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[enodessq.varlist[2:5]]
all.coef=mi.fullmod.coef[,enodessq.varlist[2:5]]
all.var=mi.fullmod.varcov[,enodessq.varlist[2:5],enodessq.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[hormon.varlist[2:5]]
all.coef=mi.fullmod.coef[,hormon.varlist[2:5]]
all.var=mi.fullmod.varcov[,hormon.varlist[2:5],hormon.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[chemo.varlist[2:5]]
all.coef=mi.fullmod.coef[,chemo.varlist[2:5]]
all.var=mi.fullmod.varcov[,chemo.varlist[2:5],chemo.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

num.param=4
pool.coef=fullmod.miSMCTVE$coefficients[logpgr.varlist[2:5]]
all.coef=mi.fullmod.coef[,logpgr.varlist[2:5]]
all.var=mi.fullmod.varcov[,logpgr.varlist[2:5],logpgr.varlist[2:5]]
source("waldtype_test_mi_rotterdam.R")
pval

```

```{r}
variable.list=c("age","sized1","sized2","grade","enodessq","hormon","chemo","logpgr")

formula.base=paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"))
```

```{r}
#-------------------------------------------
#STEP 1
#-------------------------------------------

vars.remaining=c("age","sized1","sized2","grade","enodessq","hormon","chemo","logpgr")

source("model_selection_procedure_MISMC.R")
 
mi.res
mi.stat.res

#selected covariate: age
#form for TVE: spline with 5 knots
 
```

```{r}
#-------------------------------------------
#STEP 2
#-------------------------------------------

formula.base=paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"),"+age:t+age:t.k5.1+age:t.k5.2+age:t.k5.3")

vars.remaining=c("sized1","sized2","grade","enodessq","hormon","chemo","logpgr")

source("model_selection_procedure_MISMC.R")
 
mi.res
mi.stat.res

#selected covariate: sized1
#form for TVE: spline with 5 knots
 
```

```{r}
#-------------------------------------------
#STEP 3
#-------------------------------------------

formula.base=paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"),"+age:t+age:t.k5.1+age:t.k5.2+age:t.k5.3+
                    sized1:t+sized1:t.k5.1+sized1:t.k5.2+sized1:t.k5.3")

vars.remaining=c("sized2","grade","enodessq","hormon","chemo","logpgr")

source("model_selection_procedure_MISMC.R")
 
mi.res
mi.stat.res

#selected covariate: enodessq
#form for TVE: spline with 3 knots
 
```


```{r}
#-------------------------------------------
#STEP 4
#-------------------------------------------

formula.base=paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"),"+age:t+age:t.k5.1+age:t.k5.2+age:t.k5.3+
                    sized1:t+sized1:t.k5.1+sized1:t.k5.2+sized1:t.k5.3+
                    enodessq:t+enodessq:t.k3")

vars.remaining=c("sized2","grade","hormon","chemo","logpgr")

source("model_selection_procedure_MISMC.R")
 
mi.res
mi.stat.res

#selected covariate: chemo
#form for TVE: spline with 5 knots
 
```

```{r}
#-------------------------------------------
#STEP 5
#-------------------------------------------

formula.base=paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"),"+age:t+age:t.k5.1+age:t.k5.2+age:t.k5.3+
                    sized1:t+sized1:t.k5.1+sized1:t.k5.2+sized1:t.k5.3+
                    enodessq:t+enodessq:t.k3+
                    chemo:t+chemo:t.k5.1+chemo:t.k5.2+chemo:t.k5.3")

vars.remaining=c("sized2","grade","hormon","logpgr")

source("model_selection_procedure_MISMC.R")
 
mi.res
mi.stat.res

#selected covariate: grade
#form for TVE: linear in t
```

```{r}
#-------------------------------------------
#STEP 5
#-------------------------------------------

formula.base=paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"),"+age:t+age:t.k5.1+age:t.k5.2+age:t.k5.3+
                    sized1:t+sized1:t.k5.1+sized1:t.k5.2+sized1:t.k5.3+
                    enodessq:t+enodessq:t.k3+
                    chemo:t+chemo:t.k5.1+chemo:t.k5.2+chemo:t.k5.3+grade:t")

vars.remaining=c("sized2","hormon","logpgr")

source("model_selection_procedure_MISMC.R")
 
mi.res
mi.stat.res

#selected covariate: sized2
#form for TVE: spline with 3 knots
 
```

```{r}
#-------------------------------------------
#STEP 5
#-------------------------------------------

formula.base=paste0("Surv(tstart,t,d)~",paste0(variable.list,collapse="+"),"+age:t+age:t.k5.1+age:t.k5.2+age:t.k5.3+
                    sized1:t+sized1:t.k5.1+sized1:t.k5.2+sized1:t.k5.3+
                    enodessq:t+enodessq:t.k3+
                    chemo:t+chemo:t.k5.1+chemo:t.k5.2+chemo:t.k5.3+grade:t+
                    sized2:t+sized2:t.k3")

vars.remaining=c("hormon","logpgr")

source("model_selection_procedure_MISMC.R")
 
mi.res
mi.stat.res

#STOP: no remaining p<0.05

#FINAL MODEL INCLUDES:
#age (spline with 5 knots)
#sized1 (spline with 5 knots)
#enodessq (spline with 3 knots)
#chemo (spline with 5 knots)
#grade (linear in t)
#sized2 (spline with 3 knots)
 
```

